database:
  dsn: postgresql+asyncpg://ch:yahmunguaMiep0ie@127.0.0.1:5432/ch
server:
  host: '0.0.0.0'
  cookie_secret: ohqu6aegezie9uuChidf9shuisahsiegiej4Quo9aiK3Ohhe8aisoimig4Bee9Eb
lti:
  - iss: http://localhost
    client_id: 4T1yzvAkrXm3ro7
    auth_login_url: http://localhost/mod/lti/auth.php
    auth_token_url: http://localhost/mod/lti/token.php
    key_set_url: http://localhost/mod/lti/certs.php
    private_key_file: private.pem
    public_key_file: public.pem
    deployment_ids:
      - '1'
debug: True
logging:
  version: 1
  loggers:
    compute_home:
      level: DEBUG
      qualname: compute_home
      handlers:
        - console
  formatters:
    default:
      format: '%(asctime)s %(levelname)-8s %(name)-15s %(message)s'
      datefmt: '%Y-%m-%d %H:%M:%S'
  handlers:
    console:
      class: logging.StreamHandler
      formatter: default
      level: DEBUG
      stream: ext://sys.stdout
  root:
    level: WARN
