app:
  title: Open Compute Lab
  vle:
    url: http://localhost
  containers:
    - name: tt284-block1-21j
      title: TT284 21J - Block 1
      description: |
        Virtual computing environment for Block 1 of TT284 (21J).
      host: http://localhost:8080/
      groups:
        - "2"
    - name: s397_22j
      title: S397 22J
      description: |
        Access the Genie Earth Simulation environment for block 4
        of  S397. This will allow you to run the simulations both
        when working through the module materials and for the TMA.
      host: http://localhost:8080/
      groups:
        - "2"
database:
  dsn: postgresql+asyncpg://ch:yahmunguaMiep0ie@127.0.0.1:5432/ch
server:
  host: '0.0.0.0'
  cookie_secret: ohqu6aegezie9uuChidf9shuisahsiegiej4Quo9aiK3Ohhe8aisoimig4Bee9Eb
lti:
  - iss: http://localhost
    client_id: 4T1yzvAkrXm3ro7
    auth_login_url: http://localhost/mod/lti/auth.php
    auth_token_url: http://localhost/mod/lti/token.php
    key_set_url: http://localhost/mod/lti/certs.php
    private_key_file: private.pem
    public_key_file: public.pem
    deployment_ids:
      - '1'
debug: True
logging:
  version: 1
  loggers:
    container_launcher:
      level: DEBUG
      qualname: container_launcher
      handlers:
        - console
  formatters:
    default:
      format: '%(asctime)s %(levelname)-8s %(name)-15s %(message)s'
      datefmt: '%Y-%m-%d %H:%M:%S'
  handlers:
    console:
      class: logging.StreamHandler
      formatter: default
      level: DEBUG
      stream: ext://sys.stdout
  root:
    level: WARN
