version: "3.9"
services:
  moodle:
    image: bitnami/moodle:4
    environment:
      MOODLE_DATABASE_HOST: mariadb
      MOODLE_DATABASE_PORT_NUMBER: 3306
      MOODLE_DATABASE_USER: root
      MOODLE_DATABASE_NAME: moodle
      MOODLE_DATABASE_PASSWORD: ahph3Ooshaicha7u
      MOODLE_HOST: localhost
    ports:
     - "127.0.0.1:80:8080"
    volumes:
      - moodle_data:/bitnami/moodle
      - moodledata_data:/bitnami/moodledata
volumes:
  moodle_data:
  moodledata_data:
